### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by sbeeker** [droboports/mysql#1]
In your release you mention the password is obtained from the Drobo dashboard. My issue may be clarification only.  I go to the Drobo5N dashboard and go to configure for the mysql.  This brings up a page that states the username as "root" and password is "blah blah".  When I used this in the mysqlweb page at 8033 it does not like the password.  On the configuration page it says not to change the password.  I am missing something here?  

Any help appreciated.

**Comment by ricardopadilha** [comment]
Please understand that this is not a support forum. If you need help using the apps, join us at www.drobospace.com in the DroboApps forum.

With that being said, you can generate a new root password using the button on the configuration page if the current password is not working.

If the new password still does not work, then please make sure that you are copying and pasting correctly. Sometimes a double-click on the text will select additional unwanted characters.
